"""
Run every query in sql/02_retention_analysis.sql and publish the output.

Run:  python scripts/run_analysis.py
Out:  results/findings.md
"""
import os
import re
import sqlite3

import pandas as pd

DB_PATH = os.path.join("data", "retention.db")
SQL_PATH = os.path.join("sql", "02_retention_analysis.sql")
OUT_PATH = os.path.join("results", "findings.md")


def split_queries(text):
    chunks = re.split(r"\n-{2} -{10,}\n(?=-- Q\d)", text)
    out = []
    for chunk in chunks:
        match = re.search(r"--\s*(Q\d+\..*)", chunk)
        if not match:
            continue
        out.append((match.group(1).strip(), chunk[chunk.index(match.group(0)):]))
    return out


def main():
    if not os.path.exists(DB_PATH):
        raise SystemExit("data/retention.db not found - run scripts/generate_data.py first")
    os.makedirs("results", exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    lines = [
        "# Viewer Retention Diagnostic - Results",
        "",
        "Generated by `scripts/run_analysis.py` from "
        "[`sql/02_retention_analysis.sql`](../sql/02_retention_analysis.sql).",
        "",
    ]
    for title, sql in split_queries(open(SQL_PATH).read()):
        df = pd.read_sql_query(sql, conn)
        lines += [f"## {title}", "", df.to_markdown(index=False), ""]
        print(f"[ok] {title}  ({len(df)} rows)")
    conn.close()

    open(OUT_PATH, "w").write("\n".join(lines))
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
